build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    complexity: 2
    formatting: 1

style:
  MaxLineLength:
    active: true
    maxLineLength: 120
  MagicNumber:
    active: false

complexity:
  TooManyFunctions:
    active: false
  LongParameterList:
    active: false
  ComplexMethod:
    active: true
    threshold: 15
